import { createSlice } from "@reduxjs/toolkit";

export const slice = createSlice({
    name: "activities",

    initialState: {
        value: [
            {
                id: 1,
                imgSource:"./activities/act1.jpg",
                title: "Lorem 2 Ipsum",
                text:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras dictum sit amet tortor eu pellentesque. Morbi massa eros, ullamcorper id nunc vitae, fermentum ultrices urna. Suspendisse metus tortor, vulputate eu metus sed, faucibus placerat velit. Fusce vel erat ut mauris mollis aliquam. Sed tempus lorem et eros suscipit vestibulum. Sed semper eleifend justo et laoreet. Curabitur blandit orci in ullamcorper egestas. Cras mauris magna, mattis nec bibendum pellentesque, facilisis vitae purus. Proin sodales quis nibh et facilisis. Phasellus vitae ultrices eros, sit amet aliquam ligula. Donec tortor turpis, porta ut lectus sit amet, mattis vestibulum turpis. Maecenas ullamcorper arcu ac sagittis vulputate.\n" +
                    "\n" +
                    "Sed id tellus eu ante congue porttitor. Proin eu ligula porta, mollis ipsum sed, gravida lectus. Nunc consequat mi sit amet velit posuere, hendrerit placerat ante feugiat. Proin eu odio sed magna molestie accumsan. Sed elit tellus, finibus vel scelerisque at, venenatis fermentum nibh. Suspendisse sed neque erat. Integer augue nisi, tincidunt sed consequat cursus, eleifend eu purus.\n" +
                    "\n" +
                    "Integer ex augue, efficitur eu pulvinar quis, porta ut lacus. Nullam non felis eu lacus sagittis pharetra. Pellentesque cursus imperdiet ipsum ut commodo. Mauris viverra tristique sem, ut tempor neque aliquet eu. Phasellus eu mollis leo. Maecenas pretium aliquam est quis gravida. Nunc interdum dolor vel lectus consectetur pulvinar in vel sem. Donec viverra ipsum a congue posuere. Suspendisse consectetur dapibus mauris, at aliquet libero semper vel. Nulla eget condimentum velit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut vulputate diam leo, nec semper libero rhoncus eu. Pellentesque in eros id justo feugiat dapibus. Sed a bibendum orci.\n" +
                    "\n" +
                    "Quisque sed nisi aliquet, semper risus vitae, mattis velit. Ut suscipit pulvinar quam, non euismod ligula blandit quis. Duis dignissim sit amet mi vitae lacinia. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum lacinia justo sed neque tempor consectetur. In ut urna sit amet felis dignissim rutrum ut eu quam. Vivamus quis urna vel quam consectetur convallis. Suspendisse potenti. Nam imperdiet ligula nec libero viverra placerat. In rhoncus mattis venenatis. Donec tempus quam quis enim vestibulum, a ultricies tellus porttitor. Curabitur convallis ex sapien, quis ullamcorper risus fermentum ultricies. Fusce at posuere lacus. Aenean eleifend ultrices diam. Integer ac varius ante, non vestibulum mi. Vivamus dui ligula, tristique vel suscipit sit amet, aliquam id purus.\n" +
                    "\n" +
                    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean interdum risus ac felis mattis aliquam. Nunc posuere dapibus nunc a porta. Quisque id metus egestas felis fermentum tempus non quis sem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nullam semper nulla ac augue convallis, ut tempus lacus convallis. Nunc est ex, condimentum vitae convallis sed, cursus nec eros. Ut congue sapien eget massa pretium eleifend."
            },
            {
                id: 2,
                imgSource:"./activities/act2.gif",
                title:"Lorem Ipsum",
                text:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras dictum sit amet tortor eu pellentesque. Morbi massa eros, ullamcorper id nunc vitae, fermentum ultrices urna. Suspendisse metus tortor, vulputate eu metus sed, faucibus placerat velit. Fusce vel erat ut mauris mollis aliquam. Sed tempus lorem et eros suscipit vestibulum. Sed semper eleifend justo et laoreet. Curabitur blandit orci in ullamcorper egestas. Cras mauris magna, mattis nec bibendum pellentesque, facilisis vitae purus. Proin sodales quis nibh et facilisis. Phasellus vitae ultrices eros, sit amet aliquam ligula. Donec tortor turpis, porta ut lectus sit amet, mattis vestibulum turpis. Maecenas ullamcorper arcu ac sagittis vulputate.\n" +
                    "\n" +
                    "Sed id tellus eu ante congue porttitor. Proin eu ligula porta, mollis ipsum sed, gravida lectus. Nunc consequat mi sit amet velit posuere, hendrerit placerat ante feugiat. Proin eu odio sed magna molestie accumsan. Sed elit tellus, finibus vel scelerisque at, venenatis fermentum nibh. Suspendisse sed neque erat. Integer augue nisi, tincidunt sed consequat cursus, eleifend eu purus.\n" +
                    "\n" +
                    "Integer ex augue, efficitur eu pulvinar quis, porta ut lacus. Nullam non felis eu lacus sagittis pharetra. Pellentesque cursus imperdiet ipsum ut commodo. Mauris viverra tristique sem, ut tempor neque aliquet eu. Phasellus eu mollis leo. Maecenas pretium aliquam est quis gravida. Nunc interdum dolor vel lectus consectetur pulvinar in vel sem. Donec viverra ipsum a congue posuere. Suspendisse consectetur dapibus mauris, at aliquet libero semper vel. Nulla eget condimentum velit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut vulputate diam leo, nec semper libero rhoncus eu. Pellentesque in eros id justo feugiat dapibus. Sed a bibendum orci.\n" +
                    "\n" +
                    "Quisque sed nisi aliquet, semper risus vitae, mattis velit. Ut suscipit pulvinar quam, non euismod ligula blandit quis. Duis dignissim sit amet mi vitae lacinia. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum lacinia justo sed neque tempor consectetur. In ut urna sit amet felis dignissim rutrum ut eu quam. Vivamus quis urna vel quam consectetur convallis. Suspendisse potenti. Nam imperdiet ligula nec libero viverra placerat. In rhoncus mattis venenatis. Donec tempus quam quis enim vestibulum, a ultricies tellus porttitor. Curabitur convallis ex sapien, quis ullamcorper risus fermentum ultricies. Fusce at posuere lacus. Aenean eleifend ultrices diam. Integer ac varius ante, non vestibulum mi. Vivamus dui ligula, tristique vel suscipit sit amet, aliquam id purus.\n" +
                    "\n" +
                    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean interdum risus ac felis mattis aliquam. Nunc posuere dapibus nunc a porta. Quisque id metus egestas felis fermentum tempus non quis sem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nullam semper nulla ac augue convallis, ut tempus lacus convallis. Nunc est ex, condimentum vitae convallis sed, cursus nec eros. Ut congue sapien eget massa pretium eleifend."
            },
            {
                id: 3,
                imgSource:"./activities/act3.jpg",
                title:"Lorem Ipsum",
                text:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras dictum sit amet tortor eu pellentesque. Morbi massa eros, ullamcorper id nunc vitae, fermentum ultrices urna. Suspendisse metus tortor, vulputate eu metus sed, faucibus placerat velit. Fusce vel erat ut mauris mollis aliquam. Sed tempus lorem et eros suscipit vestibulum. Sed semper eleifend justo et laoreet. Curabitur blandit orci in ullamcorper egestas. Cras mauris magna, mattis nec bibendum pellentesque, facilisis vitae purus. Proin sodales quis nibh et facilisis. Phasellus vitae ultrices eros, sit amet aliquam ligula. Donec tortor turpis, porta ut lectus sit amet, mattis vestibulum turpis. Maecenas ullamcorper arcu ac sagittis vulputate.\n" +
                    "\n" +
                    "Sed id tellus eu ante congue porttitor. Proin eu ligula porta, mollis ipsum sed, gravida lectus. Nunc consequat mi sit amet velit posuere, hendrerit placerat ante feugiat. Proin eu odio sed magna molestie accumsan. Sed elit tellus, finibus vel scelerisque at, venenatis fermentum nibh. Suspendisse sed neque erat. Integer augue nisi, tincidunt sed consequat cursus, eleifend eu purus.\n" +
                    "\n" +
                    "Integer ex augue, efficitur eu pulvinar quis, porta ut lacus. Nullam non felis eu lacus sagittis pharetra. Pellentesque cursus imperdiet ipsum ut commodo. Mauris viverra tristique sem, ut tempor neque aliquet eu. Phasellus eu mollis leo. Maecenas pretium aliquam est quis gravida. Nunc interdum dolor vel lectus consectetur pulvinar in vel sem. Donec viverra ipsum a congue posuere. Suspendisse consectetur dapibus mauris, at aliquet libero semper vel. Nulla eget condimentum velit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut vulputate diam leo, nec semper libero rhoncus eu. Pellentesque in eros id justo feugiat dapibus. Sed a bibendum orci.\n" +
                    "\n" +
                    "Quisque sed nisi aliquet, semper risus vitae, mattis velit. Ut suscipit pulvinar quam, non euismod ligula blandit quis. Duis dignissim sit amet mi vitae lacinia. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum lacinia justo sed neque tempor consectetur. In ut urna sit amet felis dignissim rutrum ut eu quam. Vivamus quis urna vel quam consectetur convallis. Suspendisse potenti. Nam imperdiet ligula nec libero viverra placerat. In rhoncus mattis venenatis. Donec tempus quam quis enim vestibulum, a ultricies tellus porttitor. Curabitur convallis ex sapien, quis ullamcorper risus fermentum ultricies. Fusce at posuere lacus. Aenean eleifend ultrices diam. Integer ac varius ante, non vestibulum mi. Vivamus dui ligula, tristique vel suscipit sit amet, aliquam id purus.\n" +
                    "\n" +
                    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean interdum risus ac felis mattis aliquam. Nunc posuere dapibus nunc a porta. Quisque id metus egestas felis fermentum tempus non quis sem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nullam semper nulla ac augue convallis, ut tempus lacus convallis. Nunc est ex, condimentum vitae convallis sed, cursus nec eros. Ut congue sapien eget massa pretium eleifend."
            },
            {
                id: 4,
                imgSource:"./activities/act4.jpg",
                title:"Lorem Ipsum",
                text:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras dictum sit amet tortor eu pellentesque. Morbi massa eros, ullamcorper id nunc vitae, fermentum ultrices urna. Suspendisse metus tortor, vulputate eu metus sed, faucibus placerat velit. Fusce vel erat ut mauris mollis aliquam. Sed tempus lorem et eros suscipit vestibulum. Sed semper eleifend justo et laoreet. Curabitur blandit orci in ullamcorper egestas. Cras mauris magna, mattis nec bibendum pellentesque, facilisis vitae purus. Proin sodales quis nibh et facilisis. Phasellus vitae ultrices eros, sit amet aliquam ligula. Donec tortor turpis, porta ut lectus sit amet, mattis vestibulum turpis. Maecenas ullamcorper arcu ac sagittis vulputate.\n" +
                    "\n" +
                    "Sed id tellus eu ante congue porttitor. Proin eu ligula porta, mollis ipsum sed, gravida lectus. Nunc consequat mi sit amet velit posuere, hendrerit placerat ante feugiat. Proin eu odio sed magna molestie accumsan. Sed elit tellus, finibus vel scelerisque at, venenatis fermentum nibh. Suspendisse sed neque erat. Integer augue nisi, tincidunt sed consequat cursus, eleifend eu purus.\n" +
                    "\n" +
                    "Integer ex augue, efficitur eu pulvinar quis, porta ut lacus. Nullam non felis eu lacus sagittis pharetra. Pellentesque cursus imperdiet ipsum ut commodo. Mauris viverra tristique sem, ut tempor neque aliquet eu. Phasellus eu mollis leo. Maecenas pretium aliquam est quis gravida. Nunc interdum dolor vel lectus consectetur pulvinar in vel sem. Donec viverra ipsum a congue posuere. Suspendisse consectetur dapibus mauris, at aliquet libero semper vel. Nulla eget condimentum velit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut vulputate diam leo, nec semper libero rhoncus eu. Pellentesque in eros id justo feugiat dapibus. Sed a bibendum orci.\n" +
                    "\n" +
                    "Quisque sed nisi aliquet, semper risus vitae, mattis velit. Ut suscipit pulvinar quam, non euismod ligula blandit quis. Duis dignissim sit amet mi vitae lacinia. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum lacinia justo sed neque tempor consectetur. In ut urna sit amet felis dignissim rutrum ut eu quam. Vivamus quis urna vel quam consectetur convallis. Suspendisse potenti. Nam imperdiet ligula nec libero viverra placerat. In rhoncus mattis venenatis. Donec tempus quam quis enim vestibulum, a ultricies tellus porttitor. Curabitur convallis ex sapien, quis ullamcorper risus fermentum ultricies. Fusce at posuere lacus. Aenean eleifend ultrices diam. Integer ac varius ante, non vestibulum mi. Vivamus dui ligula, tristique vel suscipit sit amet, aliquam id purus.\n" +
                    "\n" +
                    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean interdum risus ac felis mattis aliquam. Nunc posuere dapibus nunc a porta. Quisque id metus egestas felis fermentum tempus non quis sem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nullam semper nulla ac augue convallis, ut tempus lacus convallis. Nunc est ex, condimentum vitae convallis sed, cursus nec eros. Ut congue sapien eget massa pretium eleifend."
            },
            {
                id: 5,
                imgSource: "./activities/act5.jpg",
                title: "Lorem Ipsum",
                text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras dictum sit amet tortor eu pellentesque. Morbi massa eros, ullamcorper id nunc vitae, fermentum ultrices urna. Suspendisse metus tortor, vulputate eu metus sed, faucibus placerat velit. Fusce vel erat ut mauris mollis aliquam. Sed tempus lorem et eros suscipit vestibulum. Sed semper eleifend justo et laoreet. Curabitur blandit orci in ullamcorper egestas. Cras mauris magna, mattis nec bibendum pellentesque, facilisis vitae purus. Proin sodales quis nibh et facilisis. Phasellus vitae ultrices eros, sit amet aliquam ligula. Donec tortor turpis, porta ut lectus sit amet, mattis vestibulum turpis. Maecenas ullamcorper arcu ac sagittis vulputate.\n" +
                    "\n" +
                    "Sed id tellus eu ante congue porttitor. Proin eu ligula porta, mollis ipsum sed, gravida lectus. Nunc consequat mi sit amet velit posuere, hendrerit placerat ante feugiat. Proin eu odio sed magna molestie accumsan. Sed elit tellus, finibus vel scelerisque at, venenatis fermentum nibh. Suspendisse sed neque erat. Integer augue nisi, tincidunt sed consequat cursus, eleifend eu purus.\n" +
                    "\n" +
                    "Integer ex augue, efficitur eu pulvinar quis, porta ut lacus. Nullam non felis eu lacus sagittis pharetra. Pellentesque cursus imperdiet ipsum ut commodo. Mauris viverra tristique sem, ut tempor neque aliquet eu. Phasellus eu mollis leo. Maecenas pretium aliquam est quis gravida. Nunc interdum dolor vel lectus consectetur pulvinar in vel sem. Donec viverra ipsum a congue posuere. Suspendisse consectetur dapibus mauris, at aliquet libero semper vel. Nulla eget condimentum velit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut vulputate diam leo, nec semper libero rhoncus eu. Pellentesque in eros id justo feugiat dapibus. Sed a bibendum orci.\n" +
                    "\n" +
                    "Quisque sed nisi aliquet, semper risus vitae, mattis velit. Ut suscipit pulvinar quam, non euismod ligula blandit quis. Duis dignissim sit amet mi vitae lacinia. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum lacinia justo sed neque tempor consectetur. In ut urna sit amet felis dignissim rutrum ut eu quam. Vivamus quis urna vel quam consectetur convallis. Suspendisse potenti. Nam imperdiet ligula nec libero viverra placerat. In rhoncus mattis venenatis. Donec tempus quam quis enim vestibulum, a ultricies tellus porttitor. Curabitur convallis ex sapien, quis ullamcorper risus fermentum ultricies. Fusce at posuere lacus. Aenean eleifend ultrices diam. Integer ac varius ante, non vestibulum mi. Vivamus dui ligula, tristique vel suscipit sit amet, aliquam id purus.\n" +
                    "\n" +
                    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean interdum risus ac felis mattis aliquam. Nunc posuere dapibus nunc a porta. Quisque id metus egestas felis fermentum tempus non quis sem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nullam semper nulla ac augue convallis, ut tempus lacus convallis. Nunc est ex, condimentum vitae convallis sed, cursus nec eros. Ut congue sapien eget massa pretium eleifend."
            },
        ]
    }
});

export const activitiesData = state => state.activities.value;
export default slice.reducer;